apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      workload-type: infrastructure
      node.talos.dev/tier: infrastructure
  bgpInstances:
    - name: "instance-65001"
      localASN: 65001
      peers:
        - name: "frr-01"
          peerASN: 65000
          peerAddress: "192.168.253.20"
          peerConfigRef:
            name: frr-peer-config-infra
        - name: "frr-02"
          peerASN: 65000
          peerAddress: "192.168.253.21"
          peerConfigRef:
            name: frr-peer-config-infra
