apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-ca-cert
  namespace: argocd
data:
  rootCA.pem: |
    -----BEGIN CERTIFICATE-----
    MIIEjTCCAvWgAwIBAgIQBc014Fcw5BIYso4C98bjODANBgkqhkiG9w0BAQsFADBf
    MR4wHAYDVQQKExVta2NlcnQgZGV2ZWxvcG1lbnQgQ0ExGjAYBgNVBAsMEXJvb3RA
    ODY3N2UwOWQ1YWFmMSEwHwYDVQQDDBhta2NlcnQgcm9vdEA4Njc3ZTA5ZDVhYWYw
    HhcNMjUwNzEwMTg1NDQ2WhcNMzUwNzEwMTg1NDQ2WjBfMR4wHAYDVQQKExVta2Nl
    cnQgZGV2ZWxvcG1lbnQgQ0ExGjAYBgNVBAsMEXJvb3RAODY3N2UwOWQ1YWFmMSEw
    HwYDVQQDDBhta2NlcnQgcm9vdEA4Njc3ZTA5ZDVhYWYwggGiMA0GCSqGSIb3DQEB
    AQUAA4IBjwAwggGKAoIBgQDP7QY26BRNp0uOUczaedldTRuX0/7x8KXb1BvuJdHg
    nPDhPcjF9cFlua+e4vbwE6rzDq2Nix89AqndRFDAUNAfF1hSU7DxyNG0I4Bphh5d
    tOhSZoVeiJ0y6dGEX/VnmFFDcoTbeBDdCVeMYkrz8MVX1m8+LQnrheR4n7LOGYB/
    LW7ZWmOk/kLUo4Oc0/fTCwhe+XF9ygaBHCyYmRVLLfG8Y6ddKaqqrNYO8uSiPOaK
    kY5lIIGmplCXUuIYxXg+teWCuEHjCVDMGmnD1UzPJz7L0fe9HPzkqOPu/VfRxEAk
    biiiwFTvex13p0q3au0M4ucpU/R+ky8nUUpnRqLratNm2dpymgpk1fB0MCn0f2KT
    GTJbrt9DVh0Ow6ounlkqYYjAwtatLE1lJ9Yks65Yv/P+MDEz9ozK3Juy0dPEy1h9
    z7hiSwGrPUOQl3HLNUq6RLKYcjX595TQMdTr9zFQXCaAgNkcOzvXSTBTknnMe8pM
    dxyV8U7d5d/2Aa4UzxUYvWcCAwEAAaNFMEMwDgYDVR0PAQH/BAQDAgIEMBIGA1Ud
    EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFM8Qbb3uMiZm2REGY9ZiPzBvIZPoMA0G
    CSqGSIb3DQEBCwUAA4IBgQBDR1+KpvzWDkeuZcpwfQYupnPEAtaxmy3RTUSRSxYh
    LTUWKJMCA8dHWbo7eslBc+/BL4/Ti9OTmh/+unZFXRpGcSlJFiqhnKDihD68lGZx
    xifr6RRdcij9dEanJtdZws9ndd8dvfK/bVTWY/CG1YtXFeUJs8yh5LhpZvCT5ypX
    AJ2PFCYIoGc7m75o1tA+Xc/QKsF/UghxRtIA3g7TPpfLAEQb2kx6Z9FQxdYHxsqG
    GfkTLSmwLT7cNqs+D7zZu8sWOwDw8Q+Mvz4ca0bcbSv5gylOo8ekzjB3ypGfC6ms
    xx5o/ykuPumzJvLNwRhyMa4hDd+3dkprUKNzSSg9ZR3eg+IqYTYfn6Rz2p0jnSaj
    rZmKacP/tOf4fwKfIo5qtAgpiLG8NPRIpnu614/cZkrK0T71QZtWyKUjVLq/ZtJK
    nrGD0AFCzIzD41bWyT7zkt5hOZvmwpGkkPeC9ynxKy9lVUc+ewfVZfn25prSjA2w
    yHtz4wIvRQV9fgoXbc0nWsc=
    -----END CERTIFICATE-----
