apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: "https://192.168.253.34:8200"
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "approle"
  AVP_ROLE_ID: "<REEMPLAZAR-CON-ROLE-ID-REAL>"
  AVP_SECRET_ID: "<REEMPLAZAR-CON-SECRET-ID-REAL>"
  VAULT_CACERT: "/vault/tls/rootCA.pem"
