frr version 10.5.3
frr defaults traditional
hostname frr
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 192.168.253.20
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 192.168.253.21 remote-as 65000
 neighbor 192.168.253.21 description frr-02
 neighbor 192.168.253.111 remote-as 65001
 neighbor 192.168.253.111 description talos-infra-01
 neighbor 192.168.253.112 remote-as 65001
 neighbor 192.168.253.112 description talos-infra-02
 neighbor 192.168.253.113 remote-as 65001
 neighbor 192.168.253.113 description talos-infra-03
 neighbor 192.168.253.120 remote-as 65001
 neighbor 192.168.253.120 description talos-app-01
 neighbor 192.168.253.121 remote-as 65001
 neighbor 192.168.253.121 description talos-app-02
 !
 address-family ipv4 unicast
  neighbor 192.168.253.21 next-hop-self
  neighbor 192.168.253.111 soft-reconfiguration inbound
  neighbor 192.168.253.112 soft-reconfiguration inbound
  neighbor 192.168.253.113 soft-reconfiguration inbound
  neighbor 192.168.253.120 soft-reconfiguration inbound
  neighbor 192.168.253.121 soft-reconfiguration inbound
  maximum-paths 3
 exit-address-family
exit
!
