apiVersion: v1alpha1
kind: UserVolumeConfig
name: sdb-storage
provisioning:
  diskSelector:
    match: "disk.dev_path == '/dev/sdb'"
  minSize: 18GB
  maxSize: 32GB
  grow: true
filesystem:
  type: xfs
