- name: Create certificates directory
  file:
    path: /usr/local/share/ca-certificates
    state: directory
    mode: '0755'

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: "/usr/local/share/ca-certificates/{{ item }}"
    mode: '0644'
  loop:
    - harbor-ca.crt
    - gitea-ca.crt

- name: Update system certificates
  command: update-ca-certificates

# Certificates for Docker
- name: Create Docker certs.d directories
  file:
    path: "/etc/docker/certs.d/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "192.168.253.12"
    - "registry.harbor.local"

- name: Copy certificates for Docker
  copy:
    src: "ca.crt"
    dest: "/etc/docker/certs.d/{{ item }}/ca.crt"
    mode: '0644'
  loop:
    - "192.168.253.11"
    - "gitea.server.local"

- name: Restart Docker
  service:
    name: docker
    state: restarted

